from selenium import webdriver
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import requests
from selenium.webdriver.common.by import By
import re 

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait 

from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.common.alert import Alert
from selenium.common.exceptions import NoAlertPresentException


import time

#DRIVER_PATH = '/path/to/chromedriver'

#url = 'https://cards-of-personality-backend.onrender.com/api/deleteCard/'
#myobj = {"type":"white","deckName":"testubg-8936","secret":"6758d9c8fb144d00392d147e"}
#x = requests.post(url, json = myobj)




# Set up Chrome WebDriver
options = Options()
options.binary_location = "C:\Program Files\Mozilla Firefox\firefox.exe"
driver = webdriver.Firefox()#executable_path="C:\Scripts\geckodriver.exe", options=options)
driver.get('https://www.cardsofpersonality.com/edit-deck/testubg-8936?secret=6758d9c8fb144d00392d147e')


# Close the driver
#driver.quit()

# buttons = []
# button_cri = driver.find_elements(By.XPATH, '(//a[@class="sc-pRtAn lfmJxf"])')

# for i in range(len(button_cri)):
#     buttons.append(button_cri[i].get_attribute("button"))


# table = WebDriverWait(driver, 10).until(ec.presence_of_element_located((By.XPATH, "//table")))
# trs = WebDriverWait(table, 10).until(ec.presence_of_all_elements_located((By.XPATH, ".//tr")))
# for i in range(len(trs)):
#     table = WebDriverWait(driver, 10).until(ec.presence_of_element_located((By.XPATH, "//table")))
#     trs = WebDriverWait(table, 10).until(ec.presence_of_all_elements_located((By.XPATH, ".//tr")))
#     #tds = WebDriverWait(trs[i], 10).until(ec.presence_of_all_elements_located((By.XPATH, ".//td")))
#     #last_td = tds[-1]
#     #button = WebDriverWait(last_td, 10).until(ec.element_to_be_clickable((By.XPATH, ".//a[@class='sc-pRtAn lfmJxf']")))
#     button = WebDriverWait(table, 10).until(ec.element_to_be_clickable((By.XPATH, ".//a[@class='sc-pRtAn lfmJxf']")))
#     button.click()
#     #get your data
#     driver.back()



#matches = re.search(r'^sc.*', html, re.IGNORECASE)

#buttons = driver.find_elements(By.CLASS_NAME, re.search('^sc.*', txt))

#input[class$='put']
# '^sc.*'



#can't find the table using soup bc its automatically generated by java





# Wait for the table to appear on the page 
try:
    # You could also wait for an element inside the table, e.g., a button
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.TAG_NAME, "table"))
    )
    print("Table is loaded!")
except TimeoutError:
    print("Timed out waiting for table to load.")


# white cards - expand button
expandbut = driver.find_element(By.CLASS_NAME, 'sc-prorn.fpBoEr')
expandbut.click()

# white cards - get all current cards and delete them one by one
buttons = driver.find_elements(By.CLASS_NAME, 'sc-pbYBj.fWqrEZ')

deletedcards = 0

for pushy in buttons:
    WebDriverWait(driver, 1000000).until(EC.element_to_be_clickable(pushy)).click()
    #pushy.click()
    alert = Alert(driver)
    try:
        # Try to switch to the alert
        alert = Alert(driver)
        # If no exception is raised, the alert is present
        alert.accept()  # Accepts the alert
        #print("Alert accepted")
    except NoAlertPresentException:
        num = 567
    deletedcards += 1
    print('{} cards deleted'.format(deletedcards))



num + 1

# # Retrieve the page source
# html = driver.page_source


# # Parse the HTML with BeautifulSoup
# soup = BeautifulSoup(html, 'html.parser')

# # Find the table (use more specific selector if needed)
# table = soup.find('table')  # You can also try a more specific selector like soup.find('table', {'id': 'myTable'})

# buttons = soup.find('button', class_='sc-pRtAn lfmJxf')


# #Find all 'tr' elements with class 'athing' which contain the news titles
# allyall = soup.find_all()

# titles = soup.find_all(class_='button class')

# test4 = soup.find_all('div')

#head_tag = soup.handle_data

#buttons = soup.descendants.find_all('button')

# try:
#     # Wait for the button to be clickable
#     button_element = WebDriverWait(driver, 10).until(
#         EC.element_to_be_clickable((By.XPATH, f"//button"))
#     )
#     # Click the button
#     button_element.click()

#     # Optional: Wait for any expected changes after clicking (e.g., page updates, modal opens, etc.)
#     time.sleep(2)  # Adjust as needed (this can be a wait for page load, etc.)
# except Exception as e:
#     print(f"Could not click button: {e}")

# #for div in test4:
    

# # Loop through each title and print it
# for title in titles:
#     # Find the <a> tag within the 'titleline' span inside a 'td' with class 'title'
#     title_link = title.find('td', class_='title').find('span', class_='titleline').find('a')
#     title_text = title_link.get_text()  # Extract the text of the title
#     print(title_text)